### ISSUE TITLE
Rebuild during integration tests

### ISSUE THREAD

**Issue by joshwlewis** [Malax/libcnb.rs#355] opened 2022-02-27 04:24 UTC
Currently libcnb-test's `run_test` function generates a random OCI image name for each call:

https://github.com/Malax/libcnb.rs/blob/0ca9e3ed828f174633367c748c33164331513cf9/libcnb-test/src/lib.rs#L183

This makes it hard to perform integration tests concerning cache reuse and invalidation, since the cache is stored/retrieved based on the image name. In an ideal scenario, I'd be able to `run_test()` a second time using the same image name so the second build has an established cache to work with, and my test can verify if the cache was used/not used.

**Comment by Malax** [comment] 2022-02-27 08:46
This looks like a duplicate of #278 - can you confirm I’m not missing some subtlety?

**Comment by joshwlewis** [comment] 2022-02-27 20:39
It's the same, yeah.

**Comment by Malax** [comment] 2022-02-28 08:37
Duplicate of #278

**Closed by Malax** 2022-02-28 08:37 UTC
Labels: libcnb-test
